# Generated by Django 4.1.2 on 2023-01-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0003_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Categry',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='products',
            name='Brand',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
