# Generated by Django 4.1.2 on 2023-01-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0004_rename_categry_products_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Category',
            new_name='Categry',
        ),
    ]
