# Generated by Django 4.1.2 on 2023-01-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0007_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='subject',
        ),
    ]
