# Generated by Django 4.1.2 on 2023-01-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0008_remove_contacts_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
