# Generated by Django 4.1.2 on 2023-01-06 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0009_delete_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productss',
            name='Categry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fashionapp.category'),
        ),
    ]
