# Generated by Django 4.1.2 on 2023-01-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0010_alter_productss_categry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productss',
            name='Categry',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
